apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-page
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/naestia/argocd
    targetRevision: HEAD
    path: apps/risks/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: static-page
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
