apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikijs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.js.wiki
    chart: wiki
    targetRevision: 2.2.20
    helm:
      values: |
        postgresql:
          enabled: true
          postgresqlHost: postgres.postgres.svc.cluster.local
          postgresqlPort: 5432
          postgresqlUser: postgres
          postgresqlDatabase: wikijs
          existingSecret: wikijs
          existingSecretKey: postgresql-password
          persistence:
            enabled: false
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: wikijs.local
              paths:
                - path: /
                  pathType: Prefix
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: wikijs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
