apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oneuptime
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm-chart.oneuptime.com/
    chart: oneuptime
    targetRevision: 10.0.65
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: oneuptime
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/volumeClaimTemplates
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
