apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: outline
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://community-charts.github.io/helm-charts
      chart: outline
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/apps/outline/values.yaml
    - repoURL: https://github.com/naestia/argocd
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: outline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
