replicaCount: 1

secretKey: "placeholder"
utilsSecret: "placeholder"

postgresql:
  enabled: false

externalPostgresql:
  host: postgres.postgres.svc.cluster.local
  port: 5432
  username: postgres
  database: outline
  password: "placeholder"
  existingSecret: outline-secrets

redis:
  enabled: true
  auth:
    enabled: false
  image:
    repository: redis
    tag: 7-alpine
    registry: docker.io

fileStorage:
  mode: local
  local:
    persistence:
      enabled: true
      size: 5Gi

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: outline.local
      paths:
        - path: /
          pathType: ImplementationSpecific

service:
  type: ClusterIP
