replicaCount: 1

secretKey: "placeholder"
utilsSecret: "placeholder"

secretKeyExternalSecret:
  name: outline-secrets
  key: secret-key

utilsSecretExternalSecret:
  name: outline-secrets
  key: utils-secret

postgresql:
  enabled: false

externalPostgresql:
  host: postgres.postgres.svc.cluster.local
  port: 5432
  username: postgres
  database: outline
  password: "placeholder"
  existingSecret: outline-secrets
  secretKey: postgresql-password

redis:
  enabled: true
  auth:
    enabled: false

fileStorage:
  mode: local
  local:
    persistence:
      enabled: true
      size: 5Gi

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: outline.local
      paths:
        - path: /
          pathType: ImplementationSpecific

service:
  type: ClusterIP
