replicaCount: 1

secretKey: "placeholder"
utilsSecret: "placeholder"

postgresql:
  enabled: false

externalPostgresql:
  host: postgres.postgres.svc.cluster.local
  port: 5432
  username: postgres
  database: outline
  password: "placeholder"
  existingSecret: outline-secrets

redis:
  enabled: false

externalRedis:
  host: outline-redis
  port: 6379
  password: "placeholder"

fileStorage:
  mode: local
  local:
    persistence:
      enabled: true
      size: 5Gi

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: outline.upptec.local
      paths:
        - path: /
          pathType: ImplementationSpecific

service:
  type: ClusterIP
