apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.11.3
    helm:
      parameters:
        - name: controller.service.type
          value: NodePort
        - name: controller.hostPort.enabled
          value: "true"
        - name: controller.hostPort.ports.http
          value: "80"
        - name: controller.hostPort.ports.https
          value: "443"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
