apiVersion: apps/v1
kind: Deployment
metadata:
  name: risks
  namespace: risks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risks
  template:
    metadata:
      labels:
        app: risks
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: risks-content
