apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mira-dev
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: mira=ghcr.io/naestia/mira
    argocd-image-updater.argoproj.io/mira.update-strategy: digest
    argocd-image-updater.argoproj.io/mira.tag-name: develop
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:apps/mira/values-dev.yaml
spec:
  project: default
  source:
    repoURL: https://github.com/naestia/argocd
    targetRevision: HEAD
    path: apps/mira
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mira-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
