namespace: mira-beta
image:
  repository: ghcr.io/naestia/mira
  tag: 0.3.0-beta.1
  pullPolicy: Always
ingress:
  host: mira-beta.local
env:
  NEXTAUTH_URL: "http://mira-beta.local"
  POSTGRES_HOST: postgres.postgres.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: mira_beta
secrets:
  dbCredentials: mira-db-credentials
  authSecrets: mira-secrets
